= OpenZeppelin Defender 与 Foundry

OpenZeppelin Foundry Upgrades 可以用于通过 https://docs.openzeppelin.com/defender/[OpenZeppelin Defender] 执行部署，它允许诸如 Gas 价格估算、重新提交以及自动化字节码和源代码验证等功能。

WARNING: 无论你是否使用 `broadcast` cheatcode，Defender 部署**总是**广播到 live network。
推荐的模式是将 Defender 脚本与依赖于 network forking 和模拟的脚本分开，以避免混合模拟和 live network 数据。

== 安装

参见 xref:foundry-upgrades#installation[与 Foundry 一起使用 - 安装]。

== 前提条件
1. 安装 https://nodejs.org/[Node.js]。

2. 配置你的 `foundry.toml` 以启用 ffi、ast、build info 和存储布局：

[source,json]
----
[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
----

NOTE: 元数据也必须包含在编译器输出中，默认情况下是包含的。

[start=3]
3. 在你项目根目录下的 `.env` 文件中设置以下环境变量，使用来自 OpenZeppelin Defender 的 Team API 密钥和 secret：

[source]
----
DEFENDER_KEY=<你的 API 密钥>
DEFENDER_SECRET=<你的 API secret>
----

NOTE: 上述 API 密钥必须至少具有管理部署 (Manage Deployments) 的能力（可选地，需要管理 Relayer (Manage Relayers) 以创建具有 Relayer 的审批流程）。你可以在 https://defender.openzeppelin.com/#/settings/api-keys 配置你的 API 密钥。

== 网络选择

与 OpenZeppelin Defender 一起使用的网络由 Foundry 连接到的网络决定。
如果你想确保 Defender 使用特定的网络，请在你的 `.env` 文件中设置 `DEFENDER_NETWORK` 环境变量，例如：

[source]
----
DEFENDER_NETWORK=my-mainnet-fork
----
如果设置了，这必须是 Defender 中公共、私有或 forked 网络的名称。如果 Foundry 在设置此变量时连接到不同的网络，则不会发生部署，而是会抛出错误。

NOTE: 如果你在 Defender 中有多个具有相同 chainId 的 forked network，则需要这样做，在这种情况下，将使用名称与 `DEFENDER_NETWORK` 环境变量匹配的那个网络。

== 用法

=== 可升级合约

如果你正在部署可升级合约，请按照 xref:foundry-upgrades#installation[与 Foundry 一起使用 - 安装] 中所述使用 `Upgrades` 库，但在调用函数时设置选项 `defender.useDefenderDeploy = true`，以使所有部署都通过 OpenZeppelin Defender 进行。

**示例 1 - 部署代理**:
要部署 UUPS 代理，创建一个名为 `Defender.s.sol` 的脚本，如下所示：
[source,solidity]
----
pragma solidity ^0.8.20;

import {Script} from "forge-std/Script.sol";
import {console} from "forge-std/console.sol";

import {Defender, ApprovalProcessResponse} from "openzeppelin-foundry-upgrades/Defender.sol";
import {Upgrades, Options} from "openzeppelin-foundry-upgrades/Upgrades.sol";

import {MyContract} from "../src/MyContract.sol";

contract DefenderScript is Script {
    function setUp() public {}

    function run() public {
        ApprovalProcessResponse memory upgradeApprovalProcess = Defender.getUpgradeApprovalProcess();

        if (upgradeApprovalProcess.via == address(0)) {
            revert(string.concat("Upgrade approval process with id ", upgradeApprovalProcess.approvalProcessId, " has no assigned address"));
        }

        Options memory opts;
        opts.defender.useDefenderDeploy = true;

        address proxy = Upgrades.deployUUPSProxy(
            "MyContract.sol",
            abi.encodeCall(MyContract.initialize, ("Hello World", upgradeApprovalProcess.via)),
            opts
        );

        console.log("Deployed proxy to address", proxy);
    }
}
----

然后运行以下命令：
[source,console]
----
forge script <path to the script you created above> --force --rpc-url <RPC URL for the network you want to use>
----

上面的示例假设实现合约将其 `initialize` 函数的初始所有者地址作为参数。该脚本检索与在 Defender 中配置的升级审批流程关联的地址（例如多重签名地址），并将该地址用作初始所有者，以便它具有代理的升级权限。

此示例调用 `Upgrades.deployUUPSProxy` 函数，并使用 `defender.useDefenderDeploy` 选项，以使用 Defender 将实现合约和 UUPS 代理部署到连接的网络。该函数等待部署完成，每个合约可能需要几分钟，然后返回已部署的代理地址。在函数等待时，你可以在 OpenZeppelin Defender 的 https://defender.openzeppelin.com/v2/#/deploy[部署模块] 中监视你的部署状态。

NOTE: 如果使用 EOA 或 Safe 进行部署，则必须在脚本运行时在 Defender 中提交待处理的部署。脚本会等待每个部署完成，然后继续。

**示例 2 - 提议升级代理**:
要通过 Defender 提出升级，请创建一个如下所示的脚本：
[source,solidity]
----
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script} from "forge-std/Script.sol";
import {console} from "forge-std/console.sol";

import {MyContractV2} from "../src/MyContractV2.sol";

import {ProposeUpgradeResponse, Defender, Options} from "openzeppelin-foundry-upgrades/Defender.sol";

contract DefenderScript is Script {
    function setUp() public {}

    function run() public {
        Options memory opts;
        ProposeUpgradeResponse memory response = Defender.proposeUpgrade(
            <MY_PROXY_ADDRESS>,
            "MyContractV2.sol",
            opts
        );
        console.log("Proposal id", response.proposalId);
        console.log("Url", response.url);
    }
}
----

然后像示例 1 中一样运行脚本，然后转到生成的 URL 以查看和批准升级提案。

=== 不可升级合约

如果你正在部署不可升级的合约，请从 `Defender.sol` 导入 `Defender` 库，并使用其函数通过 OpenZeppelin Defender 部署合约。

**示例：**

要部署不可升级的合约，创建一个名为 `Defender.s.sol` 的脚本，如下所示：
[source,solidity]
----
pragma solidity ^0.8.20;

import {Script} from "forge-std/Script.sol";
import {console} from "forge-std/console.sol";

import {MyContract} from "../src/MyContract.sol";

import {Defender} from "openzeppelin-foundry-upgrades/Defender.sol";

contract DefenderScript is Script {
    function setUp() public {}

    function run() public {
        address deployed = Defender.deployContract("MyContract.sol", abi.encode("arguments for the constructor"));
        console.log("Deployed contract to address", deployed);
    }
}
----

然后运行以下命令：
[source,console]
----
forge script <path to the script you created above> --force --rpc-url <RPC URL for the network you want to use>
----

上面的示例调用 `Defender.deployContract` 函数，以使用 Defender 将指定的合约部署到连接的网络。该函数等待部署完成，这可能需要几分钟，然后返回已部署的合约地址。在函数等待时，你可以在 OpenZeppelin Defender 的 https://defender.openzeppelin.com/v2/#/deploy[部署模块] 中监视你的部署状态。

NOTE: 如果使用 EOA 或 Safe 进行部署，则必须在脚本运行时在 Defender 中提交待处理的部署。脚本会等待部署完成，然后继续。
