= 与 Foundry 一起使用

用于部署和管理可升级合约的 Foundry 库，其中包括升级安全验证。

== 安装

根据您使用的 OpenZeppelin Contracts 版本，按照以下部分之一进行操作。 新部署需要 OpenZeppelin Contracts v5。

=== 使用 OpenZeppelin Contracts v5

运行以下命令：

[source,console]
----
forge install foundry-rs/forge-std
forge install OpenZeppelin/openzeppelin-foundry-upgrades
forge install OpenZeppelin/openzeppelin-contracts-upgradeable
----

在 `remappings.txt` 中设置以下内容，替换掉这些重映射之前的任何定义：

[source]
----
@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/
@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/
----

NOTE: 上面的重映射意味着 `@openzeppelin/contracts/`（包括由此库部署的代理合约）和 `@openzeppelin/contracts-upgradeable/` 都来自您安装的 `openzeppelin-contracts-upgradeable` 子模块及其子目录，其中包括它自己的相同发行版本号的 `openzeppelin-contracts` 的传递副本。 需要此格式才能使 Etherscan 验证工作。 特别是，您单独安装的任何 `openzeppelin-contracts` 副本都不会被使用。

=== 使用 OpenZeppelin Contracts v4

运行以下命令，将 `v4.9.6` 替换为您正在使用的 OpenZeppelin Contracts 的特定版本：

[source,console]
----
forge install foundry-rs/forge-std
forge install OpenZeppelin/openzeppelin-foundry-upgrades
forge install OpenZeppelin/openzeppelin-contracts@v4.9.6
forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v4.9.6
----

在 `remappings.txt` 中设置以下内容：

[source]
----
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/
----

NOTE: 使用 `LegacyUpgrades.sol` 而不是 `Upgrades.sol` 来升级使用 OpenZeppelin Contracts v4 创建的现有部署。

=== 可选项：替代安装方法

==== NPM

按照上面的步骤，但不要运行 `forge install OpenZeppelin/openzeppelin-foundry-upgrades`，而是使用以下命令：
[source,console]
----
npm install @openzeppelin/foundry-upgrades
----

然后将以下附加行添加到 `remappings.txt` 中，以及上面描述的行：
[source,console]
----
openzeppelin-foundry-upgrades/=node_modules/@openzeppelin/foundry-upgrades/src/
----

==== Soldeer

按照上面的步骤，但不要运行 `forge install OpenZeppelin/openzeppelin-foundry-upgrades`，而是使用 https://soldeer.xyz/project/openzeppelin-foundry-upgrades 中描述的安装命令之一

然后将以下附加行添加到 `remappings.txt` 中，以及上面描述的行（将 `0.3.6` 替换为您安装的插件版本）：
[source,console]
----
openzeppelin-foundry-upgrades/=dependencies/openzeppelin-foundry-upgrades-0.3.6/src/
----

== Foundry 要求

此库需要 https://github.com/foundry-rs/forge-std[forge-std] 1.9.5 或更高版本。

== 运行之前

此库使用 https://docs.openzeppelin.com/upgrades-plugins/api-core[OpenZeppelin Upgrades CLI] 进行升级安全验证，默认情况下会在部署和升级期间运行。

如果您想能够运行升级安全验证，则需要以下内容：

. 安装 https://nodejs.org/[Node.js]。

. 配置您的 `foundry.toml` 以启用 ffi、ast、build info 和存储布局：

[source,json]
----
[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
----

[start=3]
. 如果您要从之前的版本升级您的合约，请根据 https://docs.openzeppelin.com/upgrades-plugins/api-core#define-reference-contracts[定义参考合约] 将 `@custom:oz-upgrades-from <reference>` 注释添加到您的合约的新版本，或者在调用库的函数时指定 `referenceContract` 选项。

. 在运行 Foundry 脚本或测试之前运行 `forge clean`，或者在运行 `forge script` 或 `forge test` 时包含 `--force` 选项。

如果您不想运行升级安全验证，您可以跳过上述步骤，并在调用 `Upgrades` 库的函数时使用 xref:api-foundry-upgrades.adoc#Options[`unsafeSkipAllChecks` 选项]，或者改用 `UnsafeUpgrades` 库。 请注意，这些都是危险的选项，旨在作为最后的手段使用。

=== 可选项：自定义输出目录

默认情况下，此库假定您的 Foundry 输出目录设置为 "out"。

如果您想使用自定义输出目录，请在您的 `foundry.toml` 中设置它，并为该目录提供读取权限。 例如（将 `my-output-dir` 替换为您要使用的目录）：

[source,json]
----
[profile.default]
out = "my-output-dir"
fs_permissions = [{ access = "read", path = "my-output-dir" }]
----

然后在您的项目根目录下的 `.env` 中，设置 `FOUNDRY_OUT` 环境变量以匹配自定义输出目录，例如：
[source]
----
FOUNDRY_OUT=my-output-dir
----

=== Windows 环境

如果您使用的是 Windows，请将 `OPENZEPPELIN_BASH_PATH` 环境变量设置为 `bash` 可执行文件的完全限定路径。
例如，如果您使用的是 https://gitforwindows.org/[Git for Windows]，请在您的项目的 `.env` 文件中添加以下行（使用正斜杠）：

[source]
----
OPENZEPPELIN_BASH_PATH="C:/Program Files/Git/bin/bash"
----

== 用法

根据您使用的 OpenZeppelin Contracts 的主要版本，以及您是否要运行升级安全验证和/或使用 OpenZeppelin Defender，请使用下表确定要导入哪个库：

[options="header"]
|===
| | OpenZeppelin Contracts v5 | OpenZeppelin Contracts v4
| *运行验证，支持 Defender* | `import {Upgrades} from "openzeppelin-foundry-upgrades/Upgrades.sol";` | `import {Upgrades} from "openzeppelin-foundry-upgrades/LegacyUpgrades.sol";`
| *不验证，不支持 Defender* | `import {UnsafeUpgrades} from "openzeppelin-foundry-upgrades/Upgrades.sol";` | `import {UnsafeUpgrades} from "openzeppelin-foundry-upgrades/LegacyUpgrades.sol";`
|===

在您的 Foundry 脚本或测试中导入上述库之一，例如：
[source,solidity]
----
import {Upgrades} from "openzeppelin-foundry-upgrades/Upgrades.sol";
----

还要导入您要验证、部署或升级到的实现合约，例如：
[source,solidity]
----
import {MyToken} from "src/MyToken.sol";
----

然后从导入的库中调用函数以运行验证、部署或升级。

== 例子

以下示例假定您正在使用 OpenZeppelin Contracts v5 并且想要运行升级安全验证。

=== 部署代理

部署 UUPS 代理：
[source,solidity]
----
address proxy = Upgrades.deployUUPSProxy(
    "MyContract.sol",
    abi.encodeCall(MyContract.initialize, ("initialize 函数的参数"))
);
----

部署透明代理：
[source,solidity]
----
address proxy = Upgrades.deployTransparentProxy(
    "MyContract.sol",
    INITIAL_OWNER_ADDRESS_FOR_PROXY_ADMIN,
    abi.encodeCall(MyContract.initialize, ("initialize 函数的参数"))
);
----

部署可升级信标和信标代理：
[source,solidity]
----
address beacon = Upgrades.deployBeacon("MyContract.sol", INITIAL_OWNER_ADDRESS_FOR_BEACON);

address proxy = Upgrades.deployBeaconProxy(
    beacon,
    abi.encodeCall(MyContract.initialize, ("initialize 函数的参数"))
);
----

=== 使用您的合约

像往常一样调用您的合约的函数，但请记住始终使用代理地址：
[source,solidity]
----
MyContract instance = MyContract(proxy);
instance.myFunction();
----

=== 升级代理或信标

升级透明代理或 UUPS 代理，并在升级过程中调用任意函数（例如重新初始化程序）：
[source,solidity]
----
Upgrades.upgradeProxy(
    transparentProxy,
    "MyContractV2.sol",
    abi.encodeCall(MyContractV2.foo, ("foo 的参数"))
);
----

升级透明代理或 UUPS 代理，而不调用任何其他函数：
[source,solidity]
----
Upgrades.upgradeProxy(
    transparentProxy,
    "MyContractV2.sol",
    ""
);
----

升级信标：
[source,solidity]
----
Upgrades.upgradeBeacon(beacon, "MyContractV2.sol");
----

WARNING: 升级代理或信标时，请确保新合约的 `@custom:oz-upgrades-from <reference>` 注释设置为代理或信标使用的旧实现合约的名称，或者使用 `referenceContract` 选项进行设置，例如：
[source,solidity]
----
Options memory opts;
opts.referenceContract = "MyContractV1.sol";
Upgrades.upgradeProxy(proxy, "MyContractV2.sol", "", opts);
// or Upgrades.upgradeBeacon(beacon, "MyContractV2.sol", opts);
----

TIP: 如果可能，请将旧版本的实现合约的源代码保留在项目中的某个位置，以便用作上述参考。 这要求新版本位于不同的目录、Solidity 文件中或使用不同的合约名称。 否则，如果您想对新版本使用相同的目录和名称，请保留先前部署的构建信息目录（或从项目存储库的较旧分支构建它）并按如下方式引用它：
[source,solidity]
----
Options memory opts;
opts.referenceBuildInfoDir = "/old-builds/build-info-v1";
opts.referenceContract = "build-info-v1:MyContract";
Upgrades.upgradeProxy(proxy, "MyContract.sol", "", opts);
// or Upgrades.upgradeBeacon(beacon, "MyContract.sol", opts);
----

== 覆盖率测试

要在 `forge coverage` 中启用代码覆盖率报告，请在您的测试中使用以下部署模式：直接实例化您的实现合约并使用 `UnsafeUpgrades` 库。 例如：
```solidity
address implementation = address(new MyContract());
address proxy = UnsafeUpgrades.deployUUPSProxy(
    implementation,
    abi.encodeCall(MyContract.initialize, ("initialize 函数的参数"))
);
```

WARNING: 不建议在 Forge 脚本中使用 `UnsafeUpgrades`。 它不验证您的合约是否可以安全升级，或者新的实现是否与之前的实现兼容。 在任何实际部署或升级之前，请确保运行验证，例如通过在脚本中使用 `Upgrades` 库。

== 部署和验证

使用 `forge script` 运行您的脚本以广播和部署。 请参阅 Foundry 的 https://book.getfoundry.sh/guides/scripting-with-solidity[Solidity 脚本]指南。

IMPORTANT: 执行升级时，请为 `forge script` 命令包含 `--sender <ADDRESS>` 标志，指定拥有代理或代理管理员的地址。 否则，将发生 `OwnableUnauthorizedAccount` 错误。

NOTE: 如果您想验证源代码（例如在 Etherscan 上），请为 `forge script` 命令包含 `--verify` 标志。 这将验证您的实现合约以及任何代理合约作为部署的一部分。

== 与 Defender 一起使用

如果您正在使用 OpenZeppelin Defender，请参阅 xref:foundry-defender.adoc[将 OpenZeppelin Defender 与 Foundry 结合使用]，了解如何将其用于部署。

== API

有关完整的 API 文档，请参阅 xref:api-foundry-upgrades.adoc[Foundry Upgrades API]。
