= OpenZeppelin Truffle Upgrades API

WARNING: 这个包已弃用。推荐的替代方案是使用 https://hardhat.org/[Hardhat] 以及 xref:hardhat-upgrades.adoc[Hardhat Upgrades] 插件。

`deployProxy` 和 `upgradeProxy` 函数都将返回 https://www.trufflesuite.com/docs/truffle/reference/contract-abstractions[Truffle 合约] 的实例，并且需要 Truffle 合约类（通过 `artifacts.require` 检索）作为参数。 对于 https://docs.openzeppelin.com/contracts/4.x/api/proxy#beacon[信标（beacons）]，`deployBeacon` 和 `upgradeBeacon` 都将返回一个可升级的信标实例，该实例可以与信标代理一起使用。 所有部署和升级函数都会验证实现合约是否为升级安全的，否则将失败。

[[common-options]]
== 常用选项

以下选项是一些函数通用的。

* `deployer`：应该在 Truffle 迁移期间设置为 Truffle 迁移部署器。
* `kind`：(`"uups" | "transparent" | "beacon"`) 要部署、升级或导入的代理的类型，或实现将使用的代理的类型。 `deployProxy()` 和 `upgradeProxy()` 仅支持值 `"uups" | "transparent"`。 默认为 `"transparent"`。 请参阅 xref:contracts:api:proxy.adoc#transparent-vs-uups[Transparent vs UUPS]。
* `unsafeAllow`：(`ValidationError[]`) 有选择地禁用一个或多个验证错误：
** `"external-library-linking"`：允许部署链接到实现合约的外部库。（外部库目前 xref:faq.adoc#why-cant-i-use-external-libraries[尚不支持]。）
** `"struct-definition"`, `"enum-definition"`: 过去需要使用结构体或枚举来部署合约。 现在不再需要。
** `"state-variable-assignment"`：允许在合约中分配状态变量，即使它们将存储在实现中。
** `"state-variable-immutable"`：允许使用不可变变量，这些变量不是不安全的
** `"constructor"`：允许定义构造函数。 请参阅 `constructorArgs`。
** `"delegatecall"`, `"selfdestruct"`：允许使用这些操作。 不正确地使用此选项可能会使资金面临永久损失的风险。 请参阅 xref:faq.adoc#delegatecall-selfdestruct[我可以安全地使用 `delegatecall` 和 `selfdestruct` 吗？]
** `"missing-public-upgradeto"`：允许不包含公共 `upgradeTo` 或 `upgradeToAndCall` 函数的 UUPS 实现。 启用此选项很可能会由于内置 UUPS 安全机制而导致回退。
* `unsafeAllowRenames`: (`boolean`) 配置存储布局检查以允许变量重命名。
* `unsafeSkipStorageCheck`：(`boolean`) 升级代理或信标，而无需先检查存储布局兼容性错误。 这是一个危险的选项，旨在作为最后的手段使用。
* `constructorArgs`：(`unknown[]`) 为实现合约的构造函数提供参数。 请注意，这些参数与初始化器参数不同，将用于部署实现合约本身。 可用于初始化不可变变量。
* `redeployImplementation`：(`"always" | "never" | "onchange"`) 确定是否将重新部署实现合约。 默认为 `"onchange"`。
** 如果设置为 `"always"`，则即使先前已使用相同的字节码部署了实现合约，也会始终重新部署该合约。
** 如果设置为 `"never"`，则永远不会重新部署实现合约。 如果先前未部署实现合约或在网络文件中未找到实现合约，则将引发错误。
** 如果设置为 `"onchange"`，则仅当字节码与之前的部署相比发生更改时，才会重新部署实现合约。
* `txOverrides`：(`TruffleTxOptions`) 一个 Truffle https://trufflesuite.com/docs/truffle/how-to/contracts/run-migrations/#deployerdeploycontract-args-options[options] 对象，用于覆盖交易参数，例如 `gas` 和 `gasPrice`。 适用于此选项的函数发送的所有交易，即使该函数发送多个交易。

请注意，如果使用 Solidity >=0.8.2，也可以直接在源代码中以更精细的方式指定选项 `unsafeAllow`。 请参阅 xref:faq.adoc#how-can-i-disable-checks[如何禁用某些检查？]

以下选项已被弃用。

* `unsafeAllowLinkedLibraries`：等效于在 `unsafeAllow` 中包含 `"external-library-linking"`。
* `unsafeAllowCustomTypes`：等效于在 `unsafeAllow` 中包含 `"struct-definition"` 和 `"enum-definition"`。 现在不再需要。
* `useDeployedImplementation`：(`boolean`) 等效于将 `redeployImplementation` 设置为 `"never"`。

[[deploy-proxy]]
== deployProxy

[source,ts]
----
async function deployProxy(
  Contract: ContractClass,
  args: unknown[] = [],
  opts?: {
    deployer?: Deployer,
    initializer?: string | false,
    unsafeAllow?: ValidationError[],
    constructorArgs?: unknown[],
    timeout?: number,
    pollingInterval?: number,
    redeployImplementation?: 'always' | 'never' | 'onchange',
    txOverrides?: TruffleTxOptions,
    kind?: 'uups' | 'transparent',
  },
): Promise<ContractInstance>
----

给定一个 Truffle 合约类以用作实现，创建一个 UUPS 或 Transparent 代理，并返回一个包含代理地址和实现接口的合约实例。 在迁移期间，代理地址将存储在实现合约的 artifact 中，因此您可以使用 Truffle 的 https://www.trufflesuite.com/docs/truffle/reference/contract-abstractions#-code-mycontract-deployed-code-[`deployed()`] 函数来加载它。

如果设置了 `args`，则将在代理部署期间使用提供的 `args` 调用初始化器函数 `initialize`。

如果您为同一实现合约多次调用 `deployProxy`，则将部署多个代理，但只会使用一个实现合约。

*参数：*

* `Contract` - 用作实现的 Truffle 合约类。
* `args` - 初始化器函数的参数。
* `opts` - 包含选项的对象：
** `initializer`：设置要调用的其他初始化器函数，或者指定 `false` 以禁用初始化
** 见 <<common-options>>。

*返回值：*

* 包含代理地址和实现接口的合约实例。

[[upgrade-proxy]]
== upgradeProxy

[source,ts]
----
async function upgradeProxy(
  proxy: string | ContractInstance,
  Contract: ContractClass,
  opts?: {
    deployer?: Deployer,
    call?: string | { fn: string; args?: unknown[] },
    unsafeAllow?: ValidationError[],
    unsafeAllowRenames?: boolean,
    unsafeSkipStorageCheck?: boolean,
    constructorArgs?: unknown[],
    timeout?: number,
    pollingInterval?: number,
    redeployImplementation?: 'always' | 'never' | 'onchange',
    txOverrides?: TruffleTxOptions,
    kind?: 'uups' | 'transparent',
  },
): Promise<ContractInstance>
----

将指定地址的 UUPS 或 Transparent 代理升级到新的实现合约，并返回一个包含代理地址和新实现接口的合约实例。

*参数：*

* `proxy` - 代理地址或代理合约实例。
* `Contract` - 用作新实现的 Truffle 合约类。
* `opts` - 包含选项的对象：
** `call`：允许在升级过程中执行任意函数调用。 此调用使用函数名称或签名以及可选参数进行描述。 它被批量处理到升级交易中，从而可以安全地调用迁移初始化函数。
** 见 <<common-options>>。

*返回值：*

* 包含代理地址和新实现接口的合约实例。

[[deploy-beacon]]
== deployBeacon

[source,ts]
----
async function deployBeacon(
  Contract: ContractClass,
  opts?: {
    deployer?: Deployer,
    unsafeAllow?: ValidationError[],
    constructorArgs?: unknown[],
    timeout?: number,
    pollingInterval?: number,
    redeployImplementation?: 'always' | 'never' | 'onchange',
    txOverrides?: TruffleTxOptions,
  },
): Promise<ContractInstance>
----

给定一个 Truffle 合约类以用作实现，创建一个 https://docs.openzeppelin.com/contracts/4.x/api/proxy#UpgradeableBeacon[可升级信标]，并返回信标合约实例。

*参数：*

* `Contract` - 用作实现的 Truffle 合约类。
* `opts` - 包含选项的对象：
** 见 <<common-options>>。

*返回值：*

* 信标合约实例。

*始于：*

* `@openzeppelin/truffle-upgrades@1.12.0`

[[upgrade-beacon]]
== upgradeBeacon

[source,ts]
----
async function upgradeBeacon(
  beacon: string | ContractInstance,
  Contract: ContractClass,
  opts?: {
    deployer?: Deployer,
    unsafeAllow?: ValidationError[],
    unsafeAllowRenames?: boolean,
    unsafeSkipStorageCheck?: boolean,
    constructorArgs?: unknown[],
    timeout?: number,
    pollingInterval?: number,
    redeployImplementation?: 'always' | 'never' | 'onchange',
    txOverrides?: TruffleTxOptions,
  },
): Promise<ContractInstance>
----

将指定地址的 https://docs.openzeppelin.com/contracts/4.x/api/proxy#UpgradeableBeacon[可升级信标] 升级到新的实现合约，并返回信标合约实例。

*参数：*

* `beacon` - 信标地址或信标合约实例。
* `Contract` - 用作新实现的 Truffle 合约类。
* `opts` - 包含选项的对象：
** 见 <<common-options>>。

*返回值：*

* 信标合约实例。

*始于：*

* `@openzeppelin/truffle-upgrades@1.12.0`

[[deploy-beacon-proxy]]
== deployBeaconProxy

[source,ts]
----
async function deployBeaconProxy(
  beacon: string | ContractInstance,
  attachTo: ContractClass,
  args: unknown[] = [],
  opts?: {
    deployer?: Deployer,
    initializer?: string | false,
    txOverrides?: TruffleTxOptions,
  },
): Promise<ContractInstance>
----

给定一个现有的信标合约地址和一个对应于信标当前实现合约的 Truffle 合约类，创建一个 https://docs.openzeppelin.com/contracts/4.x/api/proxy#BeaconProxy[Beacon 代理]，并返回一个包含信标代理地址和实现接口的合约实例。 如果设置了 `args`，则将在代理部署期间使用提供的参数调用初始化器函数 `initialize`。

*参数：*

* `beacon` - 信标地址或信标合约实例。
* `attachTo` - 对应于信标当前实现合约的 Truffle 合约类。
* `args` - 初始化器函数的参数。
* `opts` - 包含选项的对象：
** `initializer`：设置要调用的其他初始化器函数，或者指定 `false` 以禁用初始化

*返回值：*

* 包含信标代理地址和实现接口的合约实例。

*始于：*

* `@openzeppelin/truffle-upgrades@1.12.0`

[[force-import]]
== forceImport

[source,ts]
----
async function forceImport(
  address: string,
  deployedImpl: ContractClass,
  opts?: {
    kind?: 'uups' | 'transparent' | 'beacon',
  },
): Promise<ContractInstance>
----

强制导入现有的代理、信标或实现合约部署以与此插件一起使用。 提供现有代理、信标或实现的地址，以及已部署的实现合约的 Truffle 合约类。

CAUTION: 导入代理或信标时，`deployedImpl` 参数必须是要使用的*当前*实现合约版本的合约类，而不是您计划升级到的版本。

通过导入先前的部署来重新创建丢失的 https://docs.openzeppelin.com/upgrades-plugins/1.x/network-files[网络文件]，或者注册代理或信标以进行升级，即使它们最初不是由此插件部署的。 支持 UUPS、Transparent 和 Beacon 代理，以及信标和实现合约。

*参数：*

* `address` - 现有代理、信标或实现的地址。
* `deployedImpl` - 已部署的实现合约的 Truffle 合约类。
* `opts` - 包含选项的对象：
** `kind`：(`"uups" | "transparent" | "beacon"`) 强制将代理视为 UUPS、Transparent 或 Beacon 代理。 如果未提供，将自动检测代理类型。

*返回值：*

* 表示导入的代理、信标或实现的合约实例。

*始于：*

* `@openzeppelin/truffle-upgrades@1.13.0`

[[validate-implementation]]
== validateImplementation

[source,ts]
----
async function validateImplementation(
  Contract: ContractClass,
  opts?: {
    unsafeAllow?: ValidationError[],
    kind?: 'uups' | 'transparent' | 'beacon',
  },
): Promise<void>
----

验证实现合约而不部署它。

*参数：*

* `Contract` - 实现合约的 Truffle 合约类。
* `opts` - 包含选项的对象：
** 见 <<common-options>>。

*始于：*

* `@openzeppelin/truffle-upgrades@1.16.0`

[[deploy-implementation]]
== deployImplementation

[source,ts]
----
async function deployImplementation(
  Contract: ContractClass,
  opts?: {
    deployer?: Deployer,
    unsafeAllow?: ValidationError[],
    constructorArgs?: unknown[],
    timeout?: number,
    pollingInterval?: number,
    redeployImplementation?: 'always' | 'never' | 'onchange',
    txOverrides?: TruffleTxOptions,
    kind?: 'uups' | 'transparent' | 'beacon',
  },
): Promise<string>
----

验证并部署实现合约，并返回其地址。

*参数：*

* `Contract` - 用作实现的 Truffle 合约类。
* `opts` - 包含选项的对象：
** 见 <<common-options>>。

*返回值：*

* 实现合约的地址。

*始于：*

* `@openzeppelin/truffle-upgrades@1.16.0`

[[validate-upgrade]]
== validateUpgrade

[source,ts]
----
async function validateUpgrade(
  referenceAddressOrContract: string | ContractClass,
  newContract: ContractClass,
  opts?: {
    unsafeAllow?: ValidationError[],
    unsafeAllowRenames?: boolean,
    unsafeSkipStorageCheck?: boolean,
    kind?: 'uups' | 'transparent' | 'beacon',
  },
): Promise<void>
----

验证新的实现合约，而无需部署它，也无需实际升级到它。 将当前的实现合约与新的实现合约进行比较，以检查存储布局兼容性错误。 如果 `referenceAddressOrContract` 是当前的实现地址，则需要 `kind` 选项。

*参数：*

* `referenceAddressOrContract` - 使用当前实现的代理或信标地址，或者对应于当前实现的地址或 Truffle 合约类。
* `newContract` - 新的实现合约。
* `opts` - 包含选项的对象：
** 见 <<common-options>>。

*始于：*

* `@openzeppelin/truffle-upgrades@1.16.0`

*示例：*

验证将现有代理升级到新合约（将 `PROXY_ADDRESS` 替换为您的代理地址）：
[source,ts]
----
const { validateUpgrade } = require('@openzeppelin/truffle-upgrades');

const BoxV2 = artifacts.require('BoxV2');
await validateUpgrade(PROXY_ADDRESS, BoxV2);
----

验证在两个合约实现之间进行升级：
[source,ts]
----
const { validateUpgrade } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');
await validateUpgrade(Box, BoxV2);
----

[[prepare-upgrade]]
== prepareUpgrade

[source,ts]
----
async function prepareUpgrade(
  referenceAddressOrContract: string | ContractInstance,
  Contract: ContractClass,
  opts?: {
    deployer?: Deployer,
    unsafeAllow?: ValidationError[],
    unsafeAllowRenames?: boolean,
    unsafeSkipStorageCheck?: boolean,
    constructorArgs?: unknown[],
    timeout?: number,
    pollingInterval?: number,
    redeployImplementation?: 'always' | 'never' | 'onchange',
    txOverrides?: TruffleTxOptions,
    kind?: 'uups' | 'transparent' | 'beacon',
  },
): Promise<string>
----

验证并部署新的实现合约，并返回其地址。 如果 `referenceAddressOrContract` 是当前的实现地址，则需要 `kind` 选项。 使用此方法准备从您不直接控制或无法从 Truffle 使用的管理地址运行的升级。

*参数：*

* `referenceAddressOrContract` - 代理或信标或实现地址或合约实例。
* `Contract` - 新的实现合约。
* `opts` - 包含选项的对象：
** 见 <<common-options>>。

*返回值：*

* 新的实现合约的地址。

[[deploy-proxy-admin]]
== deployProxyAdmin

[source,ts]
----
async function deployProxyAdmin(
  opts?: {
    deployer?: Deployer,
    timeout?: number,
    pollingInterval?: number,
    txOverrides?: TruffleTxOptions,
  },
): Promise<string>
----

部署 https://docs.openzeppelin.com/contracts/4.x/api/proxy#ProxyAdmin[代理管理员] 合约并返回其地址（如果当前网络上尚未部署），或者仅返回代理管理员的地址（如果已部署）。 请注意，此插件当前仅支持每个网络使用一个代理管理员。

*参数：*

* `opts` - 包含选项的对象：
** 见 <<common-options>>。

*返回值：*

* 代理管理员的地址。

*始于：*

* `@openzeppelin/truffle-upgrades@1.16.0`

[[admin-change-proxy-admin]]
== admin.changeProxyAdmin

[source,ts]
----
async function changeProxyAdmin(
  proxyAddress: string,
  newAdmin: string,
  opts?: {
    deployer?: Deployer,
    txOverrides?: TruffleTxOptions,
  },
): Promise<void>
----

更改特定代理的管理员。

*参数：*

* `proxyAddress` - 要更改的代理的地址。
* `newAdmin` - 新的管理员地址。
* `opts` - 包含选项的对象：
** 见 <<common-options>>。

[[admin-transfer-proxy-admin-ownership]]
== admin.transferProxyAdminOwnership

[source,ts]
----
async function transferProxyAdminOwnership(
  newAdmin: string,
  opts?: {
    deployer?: Deployer,
    txOverrides?: TruffleTxOptions,
  },

): Promise<void>
----

更改代理管理员合约的所有者，该所有者是对所有代理的升级权限的默认管理员。

*参数：*

* `newAdmin` - 新的管理员地址。
* `opts` - 包含选项的对象：
** 见 <<common-options>>。

[[erc1967]]
== erc1967

[source,ts]
----
async function erc1967.getImplementationAddress(proxyAddress: string): Promise<string>;
async function erc1967.getBeaconAddress(proxyAddress: string): Promise<string>;
async function erc1967.getAdminAddress(proxyAddress: string): Promise<string>;
----

此模块中的函数提供对代理合约的 https://eips.ethereum.org/EIPS/eip-1967[ERC1967] 变量的访问。

*参数：*

* `proxyAddress` - 代理地址。

*返回值：*

* 实现、信标或管理员地址取决于调用的函数。

[[beacon]]
== beacon

[source,ts]
----
async function beacon.getImplementationAddress(beaconAddress: string): Promise<string>;
----

此模块提供了一个便捷函数，用于从信标合约获取实现地址。

*参数：*

* `beaconAddress` - 信标地址。

*返回值：*

* 实现地址。

*始于：*

* `@openzeppelin/truffle-upgrades@1.12.0`

== silenceWarnings

[source,ts]
----
function silenceWarnings()
----

NOTE: 此函数对于测试很有用，但不鼓励在生产部署脚本中使用。

禁止所有后续关于使用不安全标志的警告。 在这样做之前，会打印最后一个警告。
