= Upgrades Plugins

**将升级集成到您现有的工作流程中。** 用于在 Ethereum 上部署和管理可升级合约的 https://hardhat.org[Hardhat] 和 https://book.getfoundry.sh/[Foundry] 插件。

* 部署可升级合约。
* 升级已部署的合约。
* 管理代理管理权限。
* 在测试中轻松使用。

提示：Upgrades Plugins 仅仅是一套全面的 OpenZeppelin 工具的一部分，用于部署和保护可升级的智能合约。 xref:ROOT::upgrades.adoc[查看完整的资源列表]。

== 概述

[[usage]]
=== 安装和使用

请参阅 xref:hardhat-upgrades.adoc[Hardhat Upgrades] 或 xref:foundry-upgrades.adoc[Foundry Upgrades] 的文档。

[[how-plugins-work]]
== 插件如何工作

这些插件提供了一些函数，可以处理合约的可升级部署管理。

例如，`deployProxy` 执行以下操作：

1. 验证实现是否 xref:faq.adoc#what-does-it-mean-for-a-contract-to-be-upgrade-safe[升级安全]。

2. 部署 xref:faq.adoc#what-is-an-implementation-contract[实现合约]。请注意，Hardhat 插件首先检查是否已部署具有相同字节码的实现合约，如果已部署，则跳过此步骤。

3. 创建并初始化代理合约，以及 xref:faq.adoc#what-is-a-proxy-admin[代理管理员]（如果需要）。

当您调用 `upgradeProxy` 时：

1. 验证新的实现是否 xref:faq.adoc#what-does-it-mean-for-a-contract-to-be-upgrade-safe[升级安全] 且是否与先前的实现 xref:faq.adoc#what-does-it-mean-for-an-implementation-to-be-compatible[兼容]。

2. 部署新的 xref:faq.adoc#what-is-an-implementation-contract[实现合约]。请注意，Hardhat 插件首先检查是否已部署具有相同字节码的实现合约，如果已部署，则跳过此步骤。

3. 升级代理以使用新的实现合约。

Hardhat 插件会跟踪您在项目根目录中的 `.openzeppelin` 文件夹中部署的所有实现合约以及代理管理员。 您将在此处找到每个网络一个文件。 建议您将除开发网络之外的所有网络的文件提交到源代码控制（您可能会看到它们为 `.openzeppelin/unknown-*.json`）。

Foundry 插件不跟踪实现合约，但要求您 https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades?tab=readme-ov-file#before-running[定义参考合约]，以便验证新版本的实现的升级安全性。

[[proxy-patterns]]
== 代理模式

这些插件支持 UUPS、透明和信标代理模式。UUPS 和透明代理是单独升级的，而任何数量的信标代理可以通过升级它们指向的信标同时进行原子升级。 有关可用不同代理模式的更多详细信息，请参阅 https://docs.openzeppelin.com/contracts/api/proxy[Proxies] 的文档。

对于 UUPS 和透明代理，请使用 `deployProxy` 和 `upgradeProxy`。 对于信标代理，请使用 `deployBeacon`、`deployBeaconProxy` 和 `upgradeBeacon`。 有关示例，请参见 xref:hardhat-upgrades.adoc[Hardhat Upgrades] 和 xref:foundry-upgrades.adoc[Foundry Upgrades] 的文档。

[[managing-ownership]]
== 管理所有权

透明代理定义了一个 _admin_ 地址，该地址有权升级它们。 默认情况下，admin 是在后台部署的 xref:faq.adoc#what-is-a-proxy-admin[代理管理合约]。 请记住，代理的 _admin_ 只能升级它，但不能与实现合约交互。 阅读 xref:proxies.adoc#transparent-proxies-and-function-clashes[透明代理和函数冲突] 以获取有关此限制的更多信息。

代理管理合约还定义了一个 _owner_ 地址，该地址有权操作它。 默认情况下，如果提供了透明代理部署期间使用的 `initialOwner` 地址，则代理管理员的所有者是该地址，否则是部署期间使用的外部拥有的帐户。 您可以通过调用 Hardhat 插件中的 `admin.transferProxyAdminOwnership` 函数，或者如果使用 Foundry，则调用代理管理合约的 `transferOwnership` 函数来更改代理管理员所有者。

警告：不要重用已部署的 `ProxyAdmin`。 在 `@openzeppelin/contracts` 5.x 版本之前，提供给透明代理的地址是一个 `initialAdmin`，而不是新部署的 `ProxyAdmin` 的 `initialOwner`。 重用 `ProxyAdmin` 将禁用合约中的可升级性。

UUPS 和信标代理不使用管理地址。 UUPS 代理依赖于 https://docs.openzeppelin.com/contracts/api/proxy#UUPSUpgradeable-_authorizeUpgrade-address-[`_authorizeUpgrade`] 函数被覆盖以包括对升级机制的访问限制，而信标代理只能由其相应信标的所有者升级。

将升级代理或信标的权限转移到另一个地址后，您仍然可以使用本地设置来验证和部署实现合约。 这些插件包含一个 `prepareUpgrade` 函数，该函数将验证新的实现是否升级安全并且与先前的实现兼容，并使用您的本地 Ethereum 帐户进行部署。 然后，您可以从未管理地址或所有者地址执行升级本身。 您还可以使用 `defender.proposeUpgrade` 或 `defender.proposeUpgradeWithApproval` 函数来自动在 https://docs.openzeppelin.com/defender/[OpenZeppelin Defender] 中进行升级设置。