= 与 Truffle 一起使用

WARNING: 此包已弃用。 推荐的替代方案是使用 https://hardhat.org/[Hardhat] 以及 xref:hardhat-upgrades.adoc[Hardhat Upgrades] 插件。

此包将函数添加到您的 Truffle 迁移和测试中，以便您可以为您的合约部署和升级代理。

NOTE: 尚不支持从 https://www.trufflesuite.com/docs/truffle/getting-started/writing-external-scripts[Truffle 外部脚本] 使用。

TIP: 查看 https://forum.openzeppelin.com/t/openzeppelin-truffle-upgrades-step-by-step-tutorial/3579[分步教程]，展示了从创建、测试和部署，一直到使用 Gnosis Safe 进行升级的全过程。

[[install]]
== 安装

[source,console]
----
$ npm install --save-dev @openzeppelin/truffle-upgrades
----

此包需要 Truffle https://github.com/trufflesuite/truffle/releases/tag/v5.1.35[5.1.35 版本] 或更高版本。

[[migrations-usage]]
== 在迁移中使用

[[proxies]]
=== 代理

要在迁移中部署合约的可升级实例，请使用 `deployProxy` 函数：

[source,js]
----
// migrations/NN_deploy_upgradeable_box.js
const { deployProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');

module.exports = async function (deployer) {
  const instance = await deployProxy(Box, [42], { deployer });
  console.log('Deployed', instance.address);
};
----

这将自动检查 `Box` 合约是否是升级安全的，设置代理管理员（如果需要），为 `Box` 合约部署一个实现合约（除非之前部署已经存在一个），创建一个代理，并通过调用 `initialize(42)` 来初始化它。

然后，在未来的迁移中，您可以使用 `upgradeProxy` 函数将已部署的实例升级到新版本。 新版本可以是不同的合约（例如 `BoxV2`），或者您可以只修改现有的 `Box` 合约并重新编译它 - 该插件会注意到它已更改。

[source,js]
----
// migrations/MM_upgrade_box_contract.js
const { upgradeProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

module.exports = async function (deployer) {
  const existing = await Box.deployed();
  const instance = await upgradeProxy(existing.address, BoxV2, { deployer });
  console.log("Upgraded", instance.address);
};
----

该插件将负责比较 `BoxV2` 和之前的版本，以确保它们与升级兼容，部署新的 `BoxV2` 实现合约（除非之前部署已经存在一个），并将现有代理升级到新的实现。

[[beacon-proxies]]
=== 信标代理

您还可以使用此插件通过 `deployBeacon` 函数为您的合约部署可升级信标，然后使用 `deployBeaconProxy` 函数部署一个或多个指向它的信标代理。

[source,js]
----
// migrations/NN_deploy_upgradeable_box.js
const { deployBeacon, deployBeaconProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');

module.exports = async function (deployer) {
  const beacon = await deployBeacon(Box);
  console.log('Beacon deployed', beacon.address);

  const instance = await deployBeaconProxy(beacon, Box, [42], { deployer });
  console.log('Box deployed', instance.address);
};
----

在未来的迁移中，您可以使用 `erc1967.getBeaconAddress` 函数从已部署的信标代理实例获取信标地址，然后调用 `upgradeBeacon` 函数将该信标升级到新版本。 当信标升级后，所有指向它的信标代理都将使用新的合约实现。

[source,js]
----
// migrations/MM_upgrade_box_contract.js
const { erc1967, upgradeBeacon } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

module.exports = async function (deployer) {
  const existing = await Box.deployed();

  const beaconAddress = await erc1967.getBeaconAddress(existing.address);
  await upgradeBeacon(beaconAddress, BoxV2, { deployer });
  console.log("Beacon upgraded", beaconAddress);

  const instance = await BoxV2.at(existing.address);
};
----

[[test-usage]]
== 在测试中使用

您还可以从您的 Truffle 测试中使用该插件的功能，以防您想为升级您的合约添加测试（您应该这样做！）。 API 与迁移中的 API 相同，只是没有 `deployer` 参数。

[[proxies-tests]]
=== 代理

[source,js]
----
const { deployProxy, upgradeProxy } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

describe('upgrades', () => {
  it('works', async () => {
    const box = await deployProxy(Box, [42]);
    const box2 = await upgradeProxy(box.address, BoxV2);

    const value = await box2.value();
    assert.equal(value.toString(), '42');
  });
});
----

[[beacon-proxies-tests]]
=== 信标代理

[source,js]
----
const { deployBeacon, deployBeaconProxy, upgradeBeacon } = require('@openzeppelin/truffle-upgrades');

const Box = artifacts.require('Box');
const BoxV2 = artifacts.require('BoxV2');

describe('upgrades', () => {
  it('works', async () => {
    const beacon = await deployBeacon(Box);
    const box = await deployBeaconProxy(beacon, Box, [42]);

    await upgradeBeacon(beacon, BoxV2);
    const box2 = await BoxV2.at(box.address);

    const value = await box2.value();
    assert.equal(value.toString(), '42');
  });
});
----