= OpenZeppelin Foundry 升级 API

== 合约名称格式

合约名称必须以特定格式提供，具体取决于上下文。以下是每个上下文所需的格式：

=== Foundry 工件格式

上下文：

* `contractName` 参数
* 如果未设置 `referenceBuildInfoDir` 选项，则为 `referenceContract` 选项

可以根据 Foundry 的 https://book.getfoundry.sh/cheatcodes/get-code[getCode] 作弊码采用以下任何一种形式：

* Solidity 文件名，例如 `ContractV1.sol`
* Solidity 文件名和合约名称，例如 `ContractV1.sol:ContractV1`
* 相对于项目根目录的工件路径，例如 `out/ContractV1.sol/ContractV1.json`

=== 注解格式

上下文：

* `@custom:oz-upgrades-from <reference>` 注解
* 如果设置了 `referenceBuildInfoDir` 选项，则为 `referenceContract` 选项

可以根据 https://docs.openzeppelin.com/upgrades-plugins/api-core#define-reference-contracts[OpenZeppelin Upgrades CLI] 采用以下任何一种形式：

* 合约名称，例如 `ContractV1`
* 完全限定的合约名称，例如 `contracts/tokens/ContractV1.sol:ContractV1`

如果设置了 `referenceBuildInfoDir` 选项，包括构建信息目录短名称作为前缀，产生以下形式之一：

* 构建信息目录短名称和合约名称，例如 `build-info-v1:ContractV1`
* 构建信息目录短名称和完全限定的合约名称，例如 `build-info-v1:contracts/tokens/ContractV1.sol:ContractV1`

== 常用选项

以下选项可以与以下某些函数一起使用。 有关每个选项的详细说明，请参见 https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Options.sol[Options.sol]。

include::Options.adoc[]

== Upgrades.sol

include::Upgrades.adoc[]

== LegacyUpgrades.sol

include::LegacyUpgrades.adoc[]

== Defender.sol

include::Defender.adoc[]
