:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]
:xref-Defender-Defender-deployContract-string-: xref:#Defender-Defender-deployContract-string-
:xref-Defender-Defender-deployContract-string-struct-DefenderOptions-: xref:#Defender-Defender-deployContract-string-struct-DefenderOptions-
:xref-Defender-Defender-deployContract-string-bytes-: xref:#Defender-Defender-deployContract-string-bytes-
:xref-Defender-Defender-deployContract-string-bytes-struct-DefenderOptions-: xref:#Defender-Defender-deployContract-string-bytes-struct-DefenderOptions-
:xref-Defender-Defender-proposeUpgrade-address-string-struct-Options-: xref:#Defender-Defender-proposeUpgrade-address-string-struct-Options-
:xref-Defender-Defender-getDeployApprovalProcess--: xref:#Defender-Defender-getDeployApprovalProcess--
:xref-Defender-Defender-getUpgradeApprovalProcess--: xref:#Defender-Defender-getUpgradeApprovalProcess--
:deployContract: pass:normal[xref:#Defender-Defender-deployContract-string-[`++deployContract++`]]
:deployContract: pass:normal[xref:#Defender-Defender-deployContract-string-struct-DefenderOptions-[`++deployContract++`]]
:deployContract: pass:normal[xref:#Defender-Defender-deployContract-string-bytes-[`++deployContract++`]]
:deployContract: pass:normal[xref:#Defender-Defender-deployContract-string-bytes-struct-DefenderOptions-[`++deployContract++`]]
:proposeUpgrade: pass:normal[xref:#Defender-Defender-proposeUpgrade-address-string-struct-Options-[`++proposeUpgrade++`]]
:getDeployApprovalProcess: pass:normal[xref:#Defender-Defender-getDeployApprovalProcess--[`++getDeployApprovalProcess++`]]
:getUpgradeApprovalProcess: pass:normal[xref:#Defender-Defender-getUpgradeApprovalProcess--[`++getUpgradeApprovalProcess++`]]

[.contract]
[[Defender-Defender]]
=== `++Defender++` link:https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Defender.sol[{github-icon},role=heading-link]

[.hljs-theme-light.nopadding]
```solidity
import { Defender } from "openzeppelin-foundry-upgrades/Defender.sol";
```

用于从 Forge 脚本或测试与 OpenZeppelin Defender 交互的库。

[.contract-index]
.函数
--
* {xref-Defender-Defender-deployContract-string-}[`++deployContract(contractName)++`]
* {xref-Defender-Defender-deployContract-string-struct-DefenderOptions-}[`++deployContract(contractName, defenderOpts)++`]
* {xref-Defender-Defender-deployContract-string-bytes-}[`++deployContract(contractName, constructorData)++`]
* {xref-Defender-Defender-deployContract-string-bytes-struct-DefenderOptions-}[`++deployContract(contractName, constructorData, defenderOpts)++`]
* {xref-Defender-Defender-proposeUpgrade-address-string-struct-Options-}[`++proposeUpgrade(proxyAddress, newImplementationContractName, opts)++`]
* {xref-Defender-Defender-getDeployApprovalProcess--}[`++getDeployApprovalProcess()++`]
* {xref-Defender-Defender-getUpgradeApprovalProcess--}[`++getUpgradeApprovalProcess()++`]

--

[.contract-item]
[[Defender-Defender-deployContract-string-]]
==== `[.contract-item-name]#++deployContract++#++(string contractName) → address++` [.item-kind]#internal#

使用 OpenZeppelin Defender 将合约部署到当前网络。

警告：如果要部署可升级的合约，请勿直接使用此函数。此函数不验证合约是否升级安全。

注意：如果使用 EOA 或 Safe 进行部署，请访问 https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] 以在脚本运行时提交待处理的部署。
脚本会等待部署完成，然后继续。

*参数：*

* `contractName` (`string`) - 要部署的合约的名称，例如 "MyContract.sol" 或 "MyContract.sol:MyContract" 或相对于项目根目录的 artifact 路径

*返回*

* (`address`) - 已部署合约的地址

[.contract-item]
[[Defender-Defender-deployContract-string-struct-DefenderOptions-]]
==== `[.contract-item-name]#++deployContract++#++(string contractName, struct DefenderOptions defenderOpts) → address++` [.item-kind]#internal#

使用 OpenZeppelin Defender 将合约部署到当前网络。

警告：如果要部署可升级的合约，请勿直接使用此函数。此函数不验证合约是否升级安全。

注意：如果使用 EOA 或 Safe 进行部署，请访问 https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] 以在脚本运行时提交待处理的部署。
脚本会等待部署完成，然后继续。

*参数：*

* `contractName` (`string`) - 要部署的合约的名称，例如 "MyContract.sol" 或 "MyContract.sol:MyContract" 或相对于项目根目录的 artifact 路径
* `defenderOpts` (`struct DefenderOptions`) - Defender 部署选项。请注意，从此函数调用时，`useDefenderDeploy` 选项始终被视为 `true`。

*返回*

* (`address`) - 已部署合约的地址

[.contract-item]
[[Defender-Defender-deployContract-string-bytes-]]
==== `[.contract-item-name]#++deployContract++#++(string contractName, bytes constructorData) → address++` [.item-kind]#internal#

使用 OpenZeppelin Defender 将带有构造函数参数的合约部署到当前网络。

警告：如果要部署可升级的合约，请勿直接使用此函数。此函数不验证合约是否升级安全。

注意：如果使用 EOA 或 Safe 进行部署，请访问 https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] 以在脚本运行时提交待处理的部署。
脚本会等待部署完成，然后继续。

*参数：*

* `contractName` (`string`) - 要部署的合约的名称，例如 "MyContract.sol" 或 "MyContract.sol:MyContract" 或相对于项目根目录的 artifact 路径
* `constructorData` (`bytes`) - 编码后的构造函数参数

*返回*

* (`address`) - 已部署合约的地址

[.contract-item]
[[Defender-Defender-deployContract-string-bytes-struct-DefenderOptions-]]
==== `[.contract-item-name]#++deployContract++#++(string contractName, bytes constructorData, struct DefenderOptions defenderOpts) → address++` [.item-kind]#internal#

使用 OpenZeppelin Defender 将带有构造函数参数的合约部署到当前网络。

警告：如果要部署可升级的合约，请勿直接使用此函数。此函数不验证合约是否升级安全。

注意：如果使用 EOA 或 Safe 进行部署，请访问 https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] 以在脚本运行时提交待处理的部署。
脚本会等待部署完成，然后继续。

*参数：*

* `contractName` (`string`) - 要部署的合约的名称，例如 "MyContract.sol" 或 "MyContract.sol:MyContract" 或相对于项目根目录的 artifact 路径
* `constructorData` (`bytes`) - 编码后的构造函数参数
* `defenderOpts` (`struct DefenderOptions`) - Defender 部署选项。请注意，从此函数调用时，`useDefenderDeploy` 选项始终被视为 `true`。

*返回*

* (`address`) - 已部署合约的地址

[.contract-item]
[[Defender-Defender-proposeUpgrade-address-string-struct-Options-]]
==== `[.contract-item-name]#++proposeUpgrade++#++(address proxyAddress, string newImplementationContractName, struct Options opts) → struct ProposeUpgradeResponse++` [.item-kind]#internal#

使用 OpenZeppelin Defender 提议升级到可升级代理。

此函数验证新的实现合约与参考合约的比较，使用 Defender 部署新的实现合约，
并使用 Defender 上的升级批准流程提议升级到新的实现合约。

支持 UUPS 或 Transparent 代理。目前不支持信标代理或信标。
对于信标，请使用 `Upgrades.prepareUpgrade` 以及 Defender 上的交易提案，以将信标升级到已部署的实现。

要求设置了 `referenceContract` 选项，或者合约具有 `@custom:oz-upgrades-from <reference>` 注释。

警告：确保参考合约与代理指向的当前实现合约相同。
此函数不验证参考合约是否为当前实现。

注意：如果使用 EOA 或 Safe 进行部署，请访问 https://defender.openzeppelin.com/v2/#/deploy[Defender deploy] 以在脚本运行时提交新的实现合约的待处理部署。
脚本会等待部署完成，然后继续。

*参数：*

* `proxyAddress` (`address`) - 代理地址
* `newImplementationContractName` (`string`) - 要升级到的新实现合约的名称，例如 "MyContract.sol" 或 "MyContract.sol:MyContract" 或相对于项目根目录的 artifact 路径
* `opts` (`struct Options`) - 常用选项。请注意，从此函数调用时，`defender.useDefenderDeploy` 选项始终被视为 `true`。

*返回*

* (`struct ProposeUpgradeResponse`) - 包含升级提案的提案 ID 和 URL 的结构体

[.contract-item]
[[Defender-Defender-getDeployApprovalProcess--]]
==== `[.contract-item-name]#++getDeployApprovalProcess++#++() → struct ApprovalProcessResponse++` [.item-kind]#internal#

获取在 OpenZeppelin Defender 上为您的部署环境配置的默认部署批准流程。

*返回*

* (`struct ApprovalProcessResponse`) - 包含默认部署批准流程 ID 和关联地址（例如 Relayer、EOA 或多重签名钱包地址）的结构体。

[.contract-item]
[[Defender-Defender-getUpgradeApprovalProcess--]]
==== `[.contract-item-name]#++getUpgradeApprovalProcess++#++() → struct ApprovalProcessResponse++` [.item-kind]#internal#

获取在 OpenZeppelin Defender 上为您的部署环境配置的默认升级批准流程。
例如，这对于确定您可以在脚本中使用的默认多重签名钱包以指定为代理的所有者非常有用。

*返回*

* (`struct ApprovalProcessResponse`) - 包含默认升级批准流程 ID 和关联地址（例如多重签名或 Governor 合约地址）的结构体。